config/routes.rb
Picteract::Application.routes.draw do
  resources :home, only: [:index]
  root :to => 'home#index'

  resources :posts do
    resources :attachments, only: [:destroy]
  end

  devise_for :users

  mount_sextant if Rails.env.development?
  match '*not_found' => 'errors#handle404'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/attachment.rb
class Attachment
  include Mongoid::Document
  include Mongoid::Timestamps

  mount_uploader :file, FileUploader

  # ===== relation =====
  belongs_to :post

  # ===== model structure =====
  attr_accessible :file, :file_cache, :remove_file
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  include Mongoid::Ancestry

  # ===== relation =====
  has_ancestry

  # belongs_to :director,
  #   class_name: 'User',
  #   inverse_of: 'my_events'
  # has_and_belongs_to_many :participants,
  #   class_name: 'User',
  #   inverse_of: 'invited_events'

  has_many :attachments,
    dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true

  # ===== model structure =====

  attr_accessible :to, :body, :attachments_attributes, :parent_id , :ancestry

  attr_reader :to

  field :body, type: String

  def to=(ids)
    self.participant_ids = ids.split(",")
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  def destroy
    ap params
    @post = Post.find(params[:post_id])
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to post_path @post }
      format.json { head :no_content }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:attachments)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    if params[:post][:attachments_attributes]
      attachments = params[:post][:attachments_attributes].select{|k,v| v.key?("file")}
      params[:post][:attachments_attributes] = attachments
    end
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    if params[:post][:attachments_attributes]
      attachments = params[:post][:attachments_attributes].select{|k,v| v.key?("file")}
      params[:post][:attachments_attributes] = attachments
    end
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.haml
- model_class = Post
.page-header
  %h1=t model_class.model_name.human.pluralize

#wrapper
  #columns
    #posts
      - @posts.each do |post|
        - post.attachments.each do |attachment|
          = render 'posts/pin', attachment: attachment

-# .thumbnails
-#   - @posts.each do |post|
-#     -post.attachments.each do |attachment|
-#       -# .thumbnail
-#       = link_to image_tag(attachment.file.thumb.url, class: 'img-circle'), attachment.file.url
-#

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Picteract"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"

  %body
    = render partial: 'share/navbar'

    .container-fluid

      .row-fluid
        -# .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
        .span12
          = bootstrap_flash
          = yield

      %footer
        -# %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
= simple_nested_form_for @post, html: {multipart: true, class: 'form-horizontal'} do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .form-inputs
    = f.hidden_field :parent_id, value: @post.parent_id
    = f.input :body
    - f.fields_for :attachments do |attachment|
      = attachment.input :file
      = attachment.link_to_remove "Remove this attachment"
    .controls
      = f.link_to_add "Add attachment", :attachments
  %table
    %tr
      %th ID
      %th
    - @post.attachments.each do |attachment|
      %tr
        %td= attachment.id
        %td= link_to 'Desttory', post_attachment_path(@post.id, attachment.id), method: :delete, data: { :confirm => 'Are you sure?' }

  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/posts/_pin.html.haml
.pin.attachment
  =link_to image_tag(attachment.file.thumb.url, class: 'img-circle'),
    post_path(attachment.post)

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Body
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.body
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
-model_class = Post
.page-hedder
  %h1=t  model_class.model_name.human

%p#notice= notice

- if @post.parent
  %dl.dl-horizontal
    %dt parent
    %dd= link_to @post.parent.id, post_path(@post.parent)

%dl.dl-horizontal
  %dt= model_class.human_attribute_name(:body)
  %dd= @post.body

%dl.dl-horizontal
  %dt= model_class.human_attribute_name(:attachments)
  - @post.attachments.each do |attachment|
    %dd= link_to image_tag(attachment.file.thumb.url, class: 'img-polaroid'), attachment.file.url

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

%hr

- @post.children.each do |child|
  %dl.dl-horizontal
    %dt children
    %dd= link_to child.id, post_path(child)

%hr

- @post = Post.children_of(@post).build

= render 'form'

app/views/share/_navbar.html.haml
.navbar.navbar-fluid-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Pictract', root_path, class: 'brand'
      .container.nav-collapse
        %ul.nav
          - if user_signed_in?
            %li= link_to "Edit(#{current_user.email})", edit_user_registration_path
            %li= link_to 'Logout', destroy_user_session_path, method: :delete
          -else
            %li= link_to 'Login', '#login-modal', "data-toggle" => "modal"
            -# %li= link_to 'Login', new_user_session_path

#login-modal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Sing in

  = simple_form_for(resource, as: resource_name, url: session_path(resource_name),
    html: {class: 'form-horizontal'}) do |f|
    .modal-body
      = f.input :email, required: false, autofocus: true
      = f.input :password, required: false
      = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
    .modal-footer
      = f.button :submit, "Sign in", class: 'btn-primary'
      %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close